remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: CompCake Fairy List
description: The current list of names chosen by the cake fairy are listed here!
